### ISSUE TITLE
Error: SCardTransmit error

### ISSUE THREAD

**Issue by nuttakit-dev** [somprasongd/thai-smartcard-nodejs#22]
จังหวะเปลี่ยนบัตรครับ เเจ้ง error แบบนี้ 
A communications error with the smart card has been detected. Retry the operation.
(0x8010002f)

**Comment by somprasongd** [comment]
ใน windows รึเปล่าครับ ผมเลยรันผ่าน pm2 ให้มัน auto restart ให้ครับ

**Comment by nuttakit-dev** [comment]
ใช่ครับ windows  เดียวผมลองรันผ่าน pm2 ดูครับผม

**Comment by nuttakit-dev** [comment]
สอบถามเพิ่มเติมนะครับ ผมจะนำไปติดตั้งที่ client  ผมต้อง build ยังไงครับผม

**Comment by somprasongd** [comment]
> สอบถามเพิ่มเติมนะครับ ผมจะนำไปติดตั้งที่ client  ผมต้อง build ยังไงครับผม

ทำตามใน readme ในส่วนของ windows ได้เลยครับ หรือถ้าจะเอาพร้อมใช้งานเลยมีตัว .exe ของที่เขียนด้วย go เอาไว้อยู่ครับ

**Comment by nuttakit-dev** [comment]
ครับผม ขอบคุณมากครับ
