### ISSUE TITLE
Error: Incorrect card input

### ISSUE THREAD

**Issue by Kaymind** [somprasongd/thai-smartcard-nodejs#24]
ผมลอง clone โปรเจคและทำตามขั้นตอน install แล้ว

1. รันด้วย npm run dev
2 เปิดไฟล์ example.html

ปัญหาที่เจอ
ตอนเสียบตัวเครื่องอ่านมี log ว่า Generic EMV Smartcard Reader activated
พอเสียบบัตรปชชแล้วมีข้อความว่า Incorrect card input ลองบัตรที่มี laser id คนละแบบก็ขึ้นเหมือนกันครับ

ปล.เดี๋ยวกำลังจะลองกับเครื่องอ่านอีกตัวครับแล้วเดี๋ยวจะมา update ผลว่ายังได้ error เดิมไหมครับ

**Comment by somprasongd** [comment]
ไม่ทราบว่าบัตรออกปีไหนครับ ถ้า laser id จะมีปัญหากับบัตรที่ออกก่อนปี 2015 ถ้าผมจำไม่ผิด

ลองอันนี้ครับ https://github.com/somprasongd/go-thai-smartcard ถ้าจำไม่ผิดตัวนี้ไม่ error

**Comment by Kaymind** [comment]
บัตรที่ลองออกปี 2015 แล้วก็มีบัตรที่ออกปีนี้ครับ

**Comment by somprasongd** [comment]
บัตรปี 2015 ชิบแบบนี้อ่านไม่ได้ครับ
![image](https://github.com/somprasongd/thai-smartcard-nodejs/assets/13342959/610c2693-52bd-4974-9082-5d4e4af7a232)

ถ้าชิบแบบใหม่ อันนี้อ่านได้
![image](https://github.com/somprasongd/thai-smartcard-nodejs/assets/13342959/f8d00f14-f9b8-4cd3-baef-3f30443c8a88)

**Comment by Kaymind** [comment]
เป็นข้อจำกัดของตัวเครื่องอ่านใช่ไหมครับ

**Comment by somprasongd** [comment]
โค้ดนี้เขียนกับ java ผู้ใช้งานแจ้งว่าอ่านได้ครับบัตรแบบเก่าได้ครับ แต่ผมไม่มีบัตรทดสอบ

น่าจะเป็นที่ lib ต่อกับ hardware มั้งครับ

**Comment by Kaymind** [comment]
ตอนนี้ไปลองใช้ go แทนสามารถอ่านได้แล้วครับข้อมูลมาครบแต่ว่าตัวรูปที่เป็น base64 รูปมาไม่สมบูรณ์รูปมันซ้อนๆกันแล้วก็เหมือนมีแถบดำๆติดมาด้วยครับลอง 2 ใบเป็นทั้งคู่ครับ ตัว tag image ใส่ เป็นประมาณนี้ครับ

 ```
<img src="data:image/png;base64, xxxxxx"/>
```

**Comment by somprasongd** [comment]
บัตรผมแสดงได้ปกตินะครับ

![Screen Shot 2566-10-11 at 15 18 30](https://github.com/somprasongd/thai-smartcard-nodejs/assets/13342959/fe778fb6-7bfb-4399-b843-71066cb63f8f)

**Comment by Kaymind** [comment]
ของผมได้ออกมาแบบนี้ครับเครื่องที่ใช้ราคาน่าประมาณ 2 ร้อยกว่าบาทไม่แน่ใจว่าเกี่ยวไหมเคยใช้เครื่องหลักพันที่มี library มาให้พร้อมเลยอ่านได้ปกติ พอจะมี link ของที่เป็น java ให้ลองไหมครับกดเข้าไปแล้วขึ้น 404 ครับ

![image](https://github.com/somprasongd/thai-smartcard-nodejs/assets/54133951/0f12c649-4467-40e5-a153-f145ebf8f9d3)

**Comment by Kaymind** [comment]
> บัตรผมแสดงได้ปกตินะครับ
> 
> ![Screen Shot 2566-10-11 at 15 18 30](https://user-images.githubusercontent.com/13342959/274196447-fe778fb6-7bfb-4399-b843-71066cb63f8f.png)

ตัวนี้ใช้ go ใช่ไหมครับ

**Comment by somprasongd** [comment]
ใช่ครับ ส่วน java เป็น private project อยู่ครับ เลยเปิดไม่ได้

**Comment by Kaymind** [comment]
ขอทราบรุ่นเครื่องอ่านบัตรที่ใช้งานได้ไหมครับ

**Comment by somprasongd** [comment]
> ขอทราบรุ่นเครื่องอ่านบัตรที่ใช้งานได้ไหมครับ

![20231012_110432.jpg](https://github.com/somprasongd/thai-smartcard-nodejs/assets/13342959/d70a6882-0f92-4e11-b2c1-57bcd5510301)

ผมใช้รุ่นนี้ครับ เคยใช้กับเครื่องรุ่นอื่นสีดำ ประมาณ 300 บาท ก็ใช้งานได้ครับ พอดีมีคนยืมไปแล้วหาย เลยจำรุ่นไม่ได้ครับ

**Comment by Kaymind** [comment]
ขอบคุณครับ
